name: Deploy Spring Boot Application to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java JDK 17 (Adoptium/Temurin)
    - name: Set up Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build with Maven
    - name: Build with Maven
      run: |
        mvn clean install -DskipTests

    # Step 4: Debugging - List files in target directory to confirm JAR name
    - name: List files in target directory
      run: ls -alh ./target/

    # Step 5: Deploy to Azure Web App using the publish profile
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mtlbackend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./target/ems-backend-0.0.1-SNAPSHOT.jar  # Ensure this matches your JAR file
